# Generated by Django 3.1.7 on 2021-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('time', models.TimeField()),
                ('servings', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
